import { Alert, Button, Label, TextInput } from 'flowbite-react';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { CgTrack } from 'react-icons/cg';
import { BsCreditCardFill } from 'react-icons/bs';

import { HiInformationCircle } from 'react-icons/hi'
import Link from 'next/link';

export default function Home() {

  const router = useRouter();
  const [trackingID, setTrackingID] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    
    router.push(`/track-card?trackingID=${trackingID.replace(/[^\w\d]/ig,'')}`);
  }

  return (
    <div>
      <Head>
        <title>Kadi-go</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      {/* <div className='fixed w-full h-full bg-app-primary'></div> */}
      <main className="grid grid-col-1 lg:grid-cols-2 items-center relative w-full lg:h-screen p-8 lg:p-20 mx-auto space-y-4 z-100 backdrop-blur-2xl isolate">

        <div className='hidden lg:block fixed top-0 right-0 w-1/2 h-screen -z-10'>
          <Image className="hue-rotate-[235deg]" src="/img/asset.png" layout='fill' objectFit='cover' />
        </div>
        
        <div className='space-y-12'>

          <div className='flex items-center gap-4 mb-3'>
            <BsCreditCardFill className="text-xl text-purple-500 -rotate-45"/>
            <div className='text-2xl text-center text-neutral-700 font-bold'>kadi-go</div>
          </div>


          {/* <div className='relative w-full max-w-md h-40'>
            <Image src="/img/card.png" layout='fill' objectFit='contain' />
          </div> */}

          <div className=''>
            <p className='text-4xl font-bold text-purple-500'>
              Order for a new debit card
            </p>
            <p className='text-lg lg:w-2/3 pt-4'>
              Has your debit card expired? Let us order you a new one and get it delivered to your doorstep
            </p>
          </div>

          <div className='space-y-4'>
            <p className='font-bold'>Supported Banks</p>
            <div className='flex gap-8'>
              {/* animate-bounce before:block before:w-12 before:h-12 before:rounded-md before:bg-purple-500 before:translate-x-2 before:translate-y-2 */}
              <div className='relative w-12 h-12 rounded-md'>
                <Image className='rounded-md overflow-hidden' src="/img/banks/firstbank.png" layout="fill" objectFit="cover" />
              </div>
              
              <div className='relative w-12 h-12 rounded-md'>
                <Image className='rounded-md overflow-hidden' src="/img/banks/accessbank.png" layout="fill" objectFit="cover" />
              </div>

              <div className='relative w-12 h-12 rounded-md'>
                <Image className='rounded-md overflow-hidden' src="/img/banks/gtbank.png" layout="fill" objectFit="cover" />
              </div>

              <div className='relative w-12 h-12 rounded-md'>
                <Image className='rounded-md overflow-hidden bg-white' src="/img/banks/zenithbank.png" layout="fill" objectFit="cover" />
              </div>

            </div>
          </div>

          <div className='space-y-5'>
            <form className='grid grid-cols-12 gap-4 p-1 bg-white rounded-lg border-2 border-purple-500'>
              <input 
                className="col-span-9 block w-full outline-none border-none"
                type="text"
                placeholder="Enter Tracking ID (XXXX-XXXX-XXXX)"
                value={trackingID}
                onChange={(e) => setTrackingID(e.target.value)}
              />

              <div className='cursor-pointer col-span-3 w-full'>
                <Button className='block w-full border-none bg-gradient-to-r from-purple-500 to-purple-800' onClick={handleSubmit} type="submit">
                  <CgTrack className='text-white text-2xl' />
                  <span className="hidden lg:block pl-3 font-bold">Track</span>
                </Button>
              </div>
            </form>

            <Link href="/request-card" className="inline-block font-bold text-purple-800 hover:underline">
              <p>Request a new card</p>
            </Link>
          </div>

        </div>

        <div className='relative w-full lg:h-full h-44'>
          <Image className='scale-125' src="/img/credit-card.png" layout='fill' objectFit='cover' />
        </div>

        <div className='lg:hidden block absolute bottom-0 right-0 w-full h-80 -z-10'>
          <Image className="hue-rotate-[235deg]" src="/img/asset-mobile.png" layout='fill' objectFit='cover' />
        </div>

      </main>

    </div>
  )
}
