import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { BsBank2, BsCheckLg } from 'react-icons/bs';
import { CgEditFlipH } from 'react-icons/cg';

import ReactCardFlip from 'react-card-flip';

import genRef from '../hooks/genRandomString';

const banks = [
  {name: 'First Bank', logo: 'firstbank.png'},
  {name: 'Access Bank', logo: 'accessbank.png'},
  {name: 'GT Bank', logo: 'gtbank.png'},
  {name: 'Zenith Bank', logo: 'zenithbank.png'},
]

export default function Home() {

  const router = useRouter();
  const [showBanks, setShowBanks] = useState(false);

  const [card, setCard] = useState({
    bank: {},
    fullname: "",
    accountNo: "",
    stage: 1,
  });

  const handleSubmit = () => {
    var cards = JSON.parse(localStorage.getItem('cards')) || [];
    var trackingID = genRef(12);
    localStorage.setItem('cards', JSON.stringify([...cards, {...card, trackingID }]));
    router.push('/success?trackingID='+trackingID);
  }

  return (
    <div>
      <Head>
        <title>Get a new debit card - Kadi-go</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      {/* <div className='fixed w-full h-full bg-app-primary'></div> */}
      <main className="relative w-full p-4 max-w-sm mx-auto space-y-4 z-100 backdrop-blur-2xl isolate flex flex-col items-center">

      <p className='py-1 flex gap-3 items-center text-lg font-bold'>
        Request card
      </p>

      <div className='bg-neutral-100 w-full p-3 flex gap-4 rounded-md' onClick={() =>  setShowBanks(true)}>
        {!card?.bank?.logo ? 
          <div className='grid place-content-center relative w-6 h-6 rounded-full overflow-hidden bg-purple-200'>
            <BsBank2 className='text-purple-500 text-xs' />
          </div>
        :
          <div className='relative w-6 h-6 rounded-full overflow-hidden'>
            <Image src={`/img/banks/${card?.bank?.logo}`} layout="fill" objectFit="cover" />
          </div>
        }
        <p className=''>{card?.bank?.name || "Choose Bank"}</p>
      </div>

      <select className='bg-neutral-100 w-full p-3 rounded-md' onChange={(e) => setCard({...card, type: e.target.value }) } value={card?.type}>
        <option value="">Choose card type</option>
        <option value="verve">Verve</option>
        <option value="mastercard">Mastercard</option>
        <option value="visa">Visa</option>
      </select>

      <input className='bg-neutral-100 w-full p-3 rounded-md' onChange={(e) => setCard({...card, accountNo: e.target.value }) } value={card?.accountNo} placeholder= "Enter Account Number"/>

      <input className='bg-neutral-100 w-full p-3 rounded-md' onChange={(e) => setCard({...card, fullname: e.target.value }) } value={card?.fullname} placeholder= "Enter Fullname"/>

      <input className='bg-neutral-100 w-full p-3 rounded-md' onChange={(e) => setCard({...card, phone: e.target.value }) } value={card?.phone} placeholder= "Phone Number"/>

      <input className='bg-neutral-100 w-full p-3 rounded-md' onChange={(e) => setCard({...card, state: e.target.value }) } value={card?.state} placeholder= "State of Residence"/>

      <input className='bg-neutral-100 w-full p-3 rounded-md' onChange={(e) => setCard({...card, address: e.target.value }) } value={card?.address} placeholder= "Residential Address"/>

      <input onClick={handleSubmit} className='bg-gradient-to-r from-purple-500 to-purple-800 text-center text-sm text-white font-bold w-full p-4 rounded-md' type="submit" value="Place Order"/>



      </main>

      {showBanks && <div className='bg-[#0003] fixed top-0 left-0 w-screen h-screen flex justify-center items-center p-8'>

        <div className='bg-white shadow-2xl p-4 w-full space-y-4 rounded-md'>

          <p className='text-sm text-center font-bold'> Bank List </p>

          {banks.map(({ name, logo }, index) => (
            <div key={index} className=' active:bg-neutral-100 w-full p-4 flex gap-4 rounded-md' onClick={() => {setCard({...card, bank: { name, logo }}); setShowBanks(false)}}>
              <div className='relative w-6 h-6 rounded-full overflow-hidden'>
                <Image src={`/img/banks/${logo}`} layout="fill" objectFit="cover" />
              </div>
              <p className=''>{name}</p>
            </div>
          ))}

        </div>

      </div>}

    </div>
  )
}
