import Head from 'next/head';
import { useRouter } from 'next/router';

import Link from 'next/link';
import Script from 'next/script';


export default function Home() {

  const router = useRouter();
  const { trackingID } = router.query;

  return (
    <div>
      <Head>
        <title>Success - Kadi-go</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      {/* <div className='fixed w-full h-full bg-app-primary'></div> */}
      <main className="relative w-full p-4 max-w-sm mx-auto space-y-4 z-100 backdrop-blur-2xl isolate flex flex-col items-center">

      <p className='py-1 flex gap-3 items-center text-lg font-bold'>
        Success
      </p>

      <Script strategy="afterInteractive" src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></Script>
      <lottie-player src="https://assets9.lottiefiles.com/packages/lf20_pqnfmone.json"  background="transparent"  speed="1"  style={{ width: '150px', height: '150px', margin: 'auto' }} loop autoplay></lottie-player>

      <p className='font-bold text-4xl'>{`${trackingID?.substr(0,4)}-${trackingID?.substr(4,4)}-${trackingID?.substr(8,4)}`}</p>
      <p className='font-bold text-xs text-center text-purple-500'>Tracking ID. <br /> Please ensure this number is kept safetly</p>

      <Link className="block w-full" href={`/track-card?trackingID=${trackingID}`}>
        <p className='bg-gradient-to-r from-purple-500 to-purple-800 text-center text-sm text-white font-bold w-full p-4 rounded-md'>
          Track Order
        </p>
      </Link>


      </main>

    </div>
  )
}
