import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { BsCheckLg } from 'react-icons/bs';
import { CgEditFlipH } from 'react-icons/cg';
import ReactCardFlip from 'react-card-flip';

export default function Home() {

  const router = useRouter();
  const {trackingID} = router.query;
  const [cardFlip, setCardFlip] = useState(false);
  const [card, setCard] = useState({ });

  const cardOrder = [
    {stage: "Processing Request", desc: "Your request has been recieved and is awaiting approval after all checks has been done"},
    {stage: "Printing Card", desc: "Your card is ready to be printed"},
    {stage: "Packaged for delivery", desc: "Your card has been packaged and ready for next phase"},
    {stage: "Card sent for delivery", desc: "Your card has been sent for delivery"},
    {stage: "Card Arrived", desc: ""}
  ];


  useEffect(() => {
    setCard(JSON.parse(localStorage.getItem('cards')).find(c => trackingID === c.trackingID) || {  });
  }, [trackingID])

  return (
    <div>
      <Head>
        <title>Track Card Delivery - Kadi-go</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      {/* <div className='fixed w-full h-full bg-app-primary'></div> */}
      <main className="relative w-full p-8 max-w-sm mx-auto space-y-4 z-100 backdrop-blur-2xl isolate flex flex-col items-center">

      <p className='py-1 flex gap-3 items-center text-lg font-bold'>
        Track Card
      </p>

      <ReactCardFlip isFlipped={cardFlip} flipDirection="horizontal">
        <div onClick={() => setCardFlip(!cardFlip)} className='text-white relative p-4 w-[350px] h-[220px] bg-gradient-to-tr from-purple-500 to-purple-800 rounded-xl isolate'>

          <div className='w-12 h-10 rounded-md absolute top-20 text-center left-5 bg-gradient-to-tr from-slate-300 to-gray-400 overflow-hidden'>
            <div className='w-full h-px translate-y-3 bg-neutral-600'></div>
            <div className='w-full h-px translate-y-6 bg-neutral-600'></div>

            <div className='w-6 h-12 -translate-y-1 translate-x-3 bg-gradient-to-tr from-slate-300 to-gray-400 border border-neutral-600'></div>
            
          </div>

          <div className='w-full absolute top-5 text-right right-5'>

            <p className='font-bold text-xs'>debit</p>

          </div>

          <div className='w-full absolute bottom-5 text-center right-1/2 translate-x-1/2'>

            <p className='font-bold text-sm'>XXXX XXXX XXXX XXXX</p>
            <p className='font-bold text-sm'>XX / XX</p>
            <p className='font-bold text-sm uppercase'>{card?.fullname}</p>

          </div>

          <div className='absolute bottom-5 right-5 w-24 h-8 -z-10'>
            <Image src={`/img/banks/${card?.type}.png`} layout="fill" objectFit="contain" />
          </div>

          <div className='absolute inset-0 w-full h-full -z-[11] opacity-10'>
            <Image src="/img/banks/vector.png" layout="fill" objectFit="cover" />
          </div>

        </div>

        <div onClick={() => setCardFlip(!cardFlip)} className='relative p-4 w-[350px] h-[220px] bg-gradient-to-tr from-neutral-100 to-neutral-200 rounded-xl isolate'>

          <div className='w-full h-10 absolute top-5 left-0 text-center bg-black overflow-hidden'></div>

          <div className='w-12 h-10 rounded-md absolute top-24 text-center left-5 bg-gradient-to-tr from-slate-300 to-gray-400 overflow-hidden'></div>

          <div className='absolute top-20 text-center right-24'>
            <p className='font-bold text-xl'>XXX</p>
          </div>

          <div className='absolute bottom-5 right-5 w-24 h-8 -z-10'>
            <Image src={`/img/banks/${card?.bank?.logo}`} layout="fill" objectFit="contain" />
          </div>

        </div>
      </ReactCardFlip>
      
      <p className='py-1 font-bold flex gap-3 items-center text-xs text-purple-500 space-y-2'>
        Tap card to flip
        <CgEditFlipH className='text-sm text-purple-500' />
      </p>

      <div className='space-y-8 pt-8'>

        <div className=''>
            {cardOrder.map(({stage, desc}, index) => (
              <div key={index} className='group flex gap-4'>
                <div className='h-[88px] group-last:h-10'>
                  <div className={`relative w-6 h-6 ring-2 ring-offset-2 ${ index+1 <= card?.stage ? 'ring-purple-500 bg-purple-500 before:bg-purple-500' : 'ring-neutral-200 bg-neutral-200 before:bg-neutral-200'} rounded-full grid place-content-center
                    after:absolute after:top-full after:left-1/2 after:-translate-x-1/2 after:w-1 after:h-16 after:bg-neutral-200 after:block before:block group-last:after:hidden group-last:before:hidden after:-z-10 after:rounded-full
                    before:absolute before:top-full before:left-1/2 before:-translate-x-1/2 before:w-1 ${ index+1 < card?.stage ? 'before:h-16' : 'before:h-8'} before:-z-[9] before:rounded-full
                  `}>
                    <BsCheckLg className='text-white text-xs' />
                  </div>
                </div>
                <div className='space-y-2'>
                  <p className='font-bold'>{stage}</p>
                  <p className='text-xs text-neutral-400'>{desc}</p>
                </div>
              </div>
            ))}
        </div>
      </div>

      {/* <div className='space-y-8 pt-8'>

        <div className=''>
            <div className='flex gap-4'>
              <div className='h-[88px]'>
                <div className='relative w-6 h-6 ring-2 ring-offset-2 ring-purple-500 bg-purple-500 rounded-full grid place-content-center
                  after:absolute after:top-full after:left-1/2 after:-translate-x-1/2 after:w-1 after:h-16 after:bg-neutral-200 after:block after:-z-10 after:rounded-full
                  before:absolute before:top-full before:left-1/2 before:-translate-x-1/2 before:w-1 before:h-8 before:bg-purple-500 before:block before:-z-[9] before:rounded-full
                '>
                  <BsCheckLg className='text-white text-xs' />
                </div>
              </div>
              <div className='space-y-2'>
                <p className='font-bold'>Processing Request</p>
                <p className='text-xs text-neutral-400'>Your request has been recieved and is awaiting approval after all checks has been done</p>
              </div>
            </div>

            <div className='flex gap-4'>
              <div className='h-[88px]'>
                <div className='relative w-6 h-6 ring-2 ring-offset-2 ring-neutral-200 bg-neutral-200 rounded-full grid place-content-center
                  after:absolute after:top-full after:left-1/2 after:-translate-x-1/2 after:w-1 after:h-16 after:bg-neutral-200 after:block after:-z-10 after:rounded-full
                  before:absolute before:top-full before:left-1/2 before:-translate-x-1/2 before:w-1 before:h-8 before:bg-neutral-200 before:block before:-z-[9] before:rounded-full
                '>
                  <BsCheckLg className='text-white text-xs' />
                </div>
              </div>
              <div className='space-y-2'>
                <p className='font-bold'>Printing Card</p>
                <p className='text-xs text-neutral-400'>Your card is ready to be printed</p>
              </div>
            </div>

            <div className='flex gap-4'>
              <div className='h-[88px]'>
                <div className='relative w-6 h-6 ring-2 ring-offset-2 ring-neutral-200 bg-neutral-200 rounded-full grid place-content-center
                  after:absolute after:top-full after:left-1/2 after:-translate-x-1/2 after:w-1 after:h-16 after:bg-neutral-200 after:block after:-z-10 after:rounded-full
                  before:absolute before:top-full before:left-1/2 before:-translate-x-1/2 before:w-1 before:h-8 before:bg-neutral-200 before:block before:-z-[9] before:rounded-full
                '>
                  <BsCheckLg className='text-white text-xs' />
                </div>
              </div>
              <div className='space-y-2'>
                <p className='font-bold'>Packaged for delivery</p>
                <p className='text-xs text-neutral-400'>Your card has been packaged and ready for next phase</p>
              </div>
            </div>

            <div className='flex gap-4'>
              <div className='h-[88px]'>
                <div className='relative w-6 h-6 ring-2 ring-offset-2 ring-neutral-200 bg-neutral-200 rounded-full grid place-content-center
                  after:absolute after:top-full after:left-1/2 after:-translate-x-1/2 after:w-1 after:h-16 after:bg-neutral-200 after:block after:-z-10 after:rounded-full
                  before:absolute before:top-full before:left-1/2 before:-translate-x-1/2 before:w-1 before:h-8 before:bg-neutral-200 before:block before:-z-[9] before:rounded-full
                '>
                  <BsCheckLg className='text-white text-xs' />
                </div>
              </div>
              <div className='space-y-2'>
                <p className='font-bold'>Card sent for delivery</p>
                <p className='text-xs text-neutral-400'>Your card has been sent for delivery</p>
              </div>
            </div>

            <div className='flex gap-4'>
              <div className='h-10'>
                <div className='relative w-6 h-6 ring-2 ring-offset-2 ring-neutral-200 bg-neutral-200 rounded-full grid place-content-center
                '>
                  <BsCheckLg className='text-white text-xs' />
                </div>
              </div>
              <div className='space-y-2'>
                <p className='font-bold'>Card Arrived</p>
                <p className='text-xs text-neutral-400'></p>
              </div>
            </div>
        </div>
      </div> */}

      </main>

    </div>
  )
}
